# The data warehouse toolkit v3 chap.7
apiVersion: v1
kind: Star
tables:
- name: GeneralLedger
  metadata:
    root: true
  definition:
    type: graphql
    url: 'http://localhost:4020'
    query: 'gl'
  links:
  - to: AccountingPeriod
    key: AccountingPeriodKey
  - to: Account
    key: AccountKey
  - to: Ledger
    key: LedgerKey
  - to: Organization
    key: OrganizationKey
- name: AccountingPeriod
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'accountingperiod'
- name: Account
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'account'
- name: Ledger
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'ledger'
- name: Organization
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'organization'

