# The data warehouse toolkit v3 chap.4
apiVersion: v1
kind: Star
tables:
- name: StoreInventory
  metadata:
    root: true
  definition:
    type: graphql
    url: 'http://localhost:4020'
    query: 'storeinventories'
  links:
  - to: Date
    key: DateKey
  - to: Store
    key: StoreKey
  - to: Product
    key: ProductKey
- name: Date
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'date'
- name: Store
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'store'
- name: Product
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'product'

