# The data warehouse toolkit v3 chap.5
apiVersion: v1
kind: Star
tables:
- name: ProcurementTransaction
  metadata:
    root: true
  definition:
    type: graphql
    url: 'http://localhost:4020'
    query: 'procurementtransactions'
  links:
  - to: Date
    key: DateKey
  - to: Vendor
    key: VendorKey
  - to: Product
    key: ProductKey
  - to: ContractTerm
    key: ContractTermKey
- name: Date
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'date'
- name: Vendor
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'vendor'
- name: Product
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'product'
- name: ContractTerm
  definition:
    type: graphql-opencrud
    url: 'http://localhost:4021'
    query: 'contracterm'

